"""Where the sound came from, and whether it is real.

Every wav under ``assets/sfx/`` and the music bed are currently generated by
``scripts/gen_assets.py`` out of ffmpeg oscillators — a sine sweep standing in
for a cash register. That is the right default for a repo that has to build
and test offline with no network, and it is the wrong thing to publish, and
until now nothing distinguished the two. The taxonomy, the gain staging and
every cue that fires them were already correct; only the files were fake.

So a sidecar records provenance. ``scripts/fetch_sfx.py`` writes it when it
pulls real licence-clean effects; anything without an entry is assumed
generated, because that is what it was before this file existed.

The render says so once, the same way mock data is labelled: a video that
sounds like a synthesiser should be obvious from the log rather than from
listening to it after upload.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path

log = logging.getLogger(__name__)

SIDECAR_NAME = "SOURCES.json"

# Every generated file is normalised to this peak so one cue is never four
# times louder than the next. `fetch_sfx.py` matches it, so swapping a
# placeholder for a real effect does not change the mix.
TARGET_PEAK_DBFS = -3.0

# The room Dennis is sitting in. A desk at three in the morning, and the audio
# between words was digital silence — which is the single clearest tell that a
# cut was assembled rather than recorded. Barely audible on purpose: at -40dB
# it is felt and not heard, and it costs one more track on a mix path that
# already exists.
ROOM_TONE_NAME = "room_tone.wav"
ROOM_TONE_GAIN_DB = -40.0


@dataclass(frozen=True)
class AudioSource:
    """Provenance for one audio file."""

    name: str
    source: str = ""      # where it came from, e.g. "freesound.org/s/12345"
    licence: str = ""     # e.g. "CC0", "CC-BY-4.0"
    author: str = ""
    generated: bool = True

    @property
    def real(self) -> bool:
        return not self.generated


def sidecar_path(directory: Path) -> Path:
    return directory / SIDECAR_NAME


def load_sources(directory: Path) -> dict[str, AudioSource]:
    """Provenance for every file in `directory`, keyed by file name."""
    path = sidecar_path(directory)
    if not path.is_file():
        return {}
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        log.warning("audio provenance at %s is unreadable: %s", path, exc)
        return {}
    out: dict[str, AudioSource] = {}
    for name, entry in (raw.get("files") or {}).items():
        out[name] = AudioSource(
            name=name,
            source=str(entry.get("source", "")),
            licence=str(entry.get("licence", "")),
            author=str(entry.get("author", "")),
            generated=bool(entry.get("generated", False)),
        )
    return out


def save_sources(directory: Path, sources: dict[str, AudioSource]) -> Path:
    """Write the sidecar. Overwrites whatever was there."""
    path = sidecar_path(directory)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "note": "Provenance for the files in this directory. An entry with "
                "generated=true is a synthesised placeholder, not a real "
                "effect — see scripts/fetch_sfx.py.",
        "files": {
            name: {"source": s.source, "licence": s.licence,
                   "author": s.author, "generated": s.generated}
            for name, s in sorted(sources.items())
        },
    }
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return path


def generated_audio(settings) -> list[str]:
    """Every audio file the render would play that is a placeholder.

    A file with no provenance entry counts as generated — that is what every
    one of them was before the sidecar existed, and assuming the flattering
    answer for an unknown is how a synthesised cash register reaches an
    upload.
    """
    out: list[str] = []
    for sub in ("sfx", "music"):
        directory = settings.assets_dir / sub
        if not directory.is_dir():
            continue
        known = load_sources(directory)
        for path in sorted(directory.iterdir()):
            if path.suffix.lower() not in (".wav", ".mp3", ".m4a", ".ogg"):
                continue
            entry = known.get(path.name)
            if entry is None or entry.generated:
                out.append(f"{sub}/{path.name}")
    return out


def audio_banner(settings) -> str:
    """One line for the log when the render is playing synthesised audio."""
    placeholders = generated_audio(settings)
    if not placeholders:
        return ""
    return (
        f"PLACEHOLDER AUDIO — {len(placeholders)} of the sound files this "
        f"render plays are ffmpeg oscillators, not real effects "
        f"({', '.join(placeholders[:4])}"
        f"{', ...' if len(placeholders) > 4 else ''}). "
        f"Run scripts/fetch_sfx.py before publishing."
    )
