#!/usr/bin/env python3
"""Materialise the design kit: run the engine, write the artwork, verify it.

    python scripts/ingest_kit.py kit            build from the delivery in kit/
    python scripts/ingest_kit.py kit --outfit cardigan
    python scripts/ingest_kit.py --check        verify what is already on disk

THE KIT IS CODE, NOT PICTURES. `kit/engine/build.js` declares every asset as an
author plus a seed plus arguments, and `BUILD.draw()` reproduces it byte for
byte. Outfits, boil frames and aspects are arguments — which is why the delivery
is 1.4 MB of JS rather than 860 MB of PNGs, and why five outfits are not five
families somebody has to re-export.

So ingest RUNS the engine and writes real files out, and the render path then
loads plain PNGs exactly as it always did. Node is a build-time dependency and
must never appear in the render path: a bug in `plates.js` has to break a build,
not a published video. Nothing under `pipeline/` imports this module or shells
out to node — `tests/test_ingest.py` holds that line.

Nothing here trusts anything. The engine's own manifest is checked against the
manifest the delivery shipped, every frame it names is opened and measured, and
a PNG on disk that the registry does not name is a failure rather than dead
weight nobody notices. Any single failure exits non-zero and says DO NOT COMMIT,
because a missing asset must never reach a render and degrade quietly into an
empty box.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from pipeline.plates import (  # noqa: E402
    CHAPTER_TYPES, PLATES_DIRNAME, REGISTRY_NAME, PlateError, load_registry,
)

REPO = Path(__file__).resolve().parents[1]
DRIVER = REPO / "scripts" / "kit_engine.js"

# The families the delivery ships. A family on disk that is not here, or one
# here with nothing on disk, is a delivery that changed shape without anyone
# saying so — which is the moment to look, not to carry on.
EXPECTED_FAMILIES = frozenset({
    "annotations", "cards", "charts", "cycles", "figures", "frames", "host",
    "overlays", "paper", "peers", "room", "shorts", "structure", "tables",
})


def _node(delivery: Path, out: Path, outfit: str,
          only: str = "") -> dict:
    """Run the engine. Its stdout is the registry; stderr is for the operator.

    `only` restricts the build to one family. That is the whole of the
    batched route: fourteen processes instead of one, each returning its
    memory to the OS before the next starts.
    """
    if not DRIVER.exists():
        raise PlateError(f"missing engine driver {DRIVER}")
    cmd = ["node", str(DRIVER), "--kit", str(delivery), "--out", str(out),
           "--outfit", outfit]
    if only:
        cmd += ["--only", only]
    print(f"  $ {' '.join(cmd)}")
    try:
        proc = subprocess.run(cmd, cwd=REPO, capture_output=True, text=True)
    except FileNotFoundError:
        raise PlateError(
            "node is not on PATH. The kit is JS and is rendered at INGEST — "
            "install Node 18+ and run `npm ci` for the rasteriser. The render "
            "path needs neither."
        ) from None
    if proc.stderr.strip():
        for line in proc.stderr.strip().splitlines():
            print(f"  {line}")
    if proc.returncode != 0:
        raise PlateError(f"the engine failed (exit {proc.returncode})")
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise PlateError(f"the engine did not emit a registry: {exc}") from None


# The per-family manifest's table of plates, by the name it is under.
#
# delta-14 renamed it `assets` -> `plates`. Both are read, and reading both
# is not the same mistake as accepting two LOCATIONS for the file: a
# manifest is generated by the engine and its top-level key is a fact about
# which pack drew it, where a second search path is a decision about where
# things live. A pack older than delta-14 still reconciles.
_MANIFEST_TABLES = ("plates", "assets")


def _plate_table(raw: dict) -> dict:
    for name in _MANIFEST_TABLES:
        table = raw.get(name)
        if isinstance(table, dict) and table:
            return table
    return {}


def _node_batched(delivery: Path, out: Path, outfit: str) -> dict:
    """The whole library, one family per process (§5).

    THE INGEST IS MEMORY-BOUND, and the cost is retention rather than any
    one plate: the largest single frame is a room at about 1.5 MB of SVG and
    the whole library serialised survives, but a caller that walks the
    library and keeps the plate objects holds 924 path lists, slot tables
    and manifests at once. That is what the kernel kills.

    A family is the unit because it is the largest chunk that built in one
    pass when the manifests were generated, and because the manifests are
    already per-family — so a batch that fails names a file that can be
    regenerated alone rather than invalidating the run.

    What it costs, stated rather than buried: fourteen process starts,
    fourteen engine parses, and no shared work between them. It is slower
    than one pass and it is meant to be. It also cannot catch a
    cross-family defect, because nothing in it ever sees two families at
    once — the same blindness the per-family manifest generation has.
    """
    merged: dict = {"assets": {}}
    families = sorted(EXPECTED_FAMILIES)
    for i, family in enumerate(families, 1):
        print(f"  [{i}/{len(families)}] {family}")
        part = _node(delivery, out, outfit, only=family)
        drawn = part.get("assets") or {}
        if not drawn:
            raise PlateError(
                f"the {family} batch drew nothing. A batched run is fourteen "
                f"independent builds, so this one family can be retried with "
                f"`--only {family}` without redoing the other thirteen.")
        overlap = set(merged["assets"]) & set(drawn)
        if overlap:
            raise PlateError(
                f"the {family} batch redrew {len(overlap)} plate(s) another "
                f"family already drew ({sorted(overlap)[:3]}) — the batches "
                f"are supposed to partition the library, and merging them is "
                f"only sound because they do")
        merged["assets"].update(drawn)
        for key, value in part.items():
            if key != "assets":
                merged.setdefault(key, value)
    print(f"  batched: {len(merged['assets'])} plates across "
          f"{len(families)} families")
    return merged


def _build_one(delivery: Path, staged: Path, outfit: str, family: str) -> int:
    """`--only FAMILY`: draw one family and reconcile it against its own
    manifest. Deliberately does NOT install — a registry holding one family
    is not a kit, and writing one would leave the render path pointing at a
    library with thirteen holes in it."""
    built = _node(delivery, staged, outfit, only=family)
    drawn = built.get("assets") or {}
    shipped = {k: v for k, v in _shipped_manifests(delivery).items()
               if k.split("/", 1)[0] == family}
    problems = _reconcile(drawn, shipped)
    if problems:
        print(f"\nFAILED — {family} disagrees with its manifest "
              f"({len(problems)}):")
        for p in problems[:20]:
            print(f"  {p}")
        return 1
    print(f"  {family}: {len(drawn)} plates match the shipped manifest")
    print("\nNOT INSTALLED — `--only` verifies one family; run the full "
          "ingest (or `--batched`) to write a registry.")
    return 0


def _shipped_manifests(delivery: Path) -> dict:
    """Every asset the delivery's own manifests declare, merged.

    ONE LOCATION, deliberately: `kit/<family>/manifest.json`. delta-14 ships
    its copies under `kit/manifests/<family>/`, which this glob does not
    match — and widening it would leave two valid homes for a generated
    file, so the drop's manifests are placed in the repository's layout
    instead. With them anywhere else this returns {} and `_reconcile`
    compares the engine's output against nothing at all, silently.
    """
    out: dict = {}
    for m in sorted(delivery.glob("*/manifest.json")):
        raw = json.loads(m.read_text(encoding="utf-8"))
        out.update(_plate_table(raw))
    return out


def _reconcile(built: dict, shipped: dict) -> list[str]:
    """The engine drew it; the delivery said what it would be. They must agree.

    This is the check that makes "the engine is the source, the PNGs are a
    cache" safe to act on. If a re-run of the engine produced different slot
    geometry from the manifests the artwork was signed off against, every
    downstream coordinate is wrong and no rendered frame would look obviously
    broken — the figures would just sit somewhere else.
    """
    problems: list[str] = []
    for key in sorted(set(shipped) - set(built)):
        problems.append(f"{key}: the delivery declares it, the engine did not draw it")
    for key in sorted(set(built) - set(shipped)):
        problems.append(f"{key}: the engine drew it, no manifest declares it")
    for key in sorted(set(built) & set(shipped)):
        b, s = built[key], shipped[key]
        # `typeRoles` IS RECONCILED, and learning that cost a silent 139.
        #
        # It carries the type every word on screen is set in AND the role-level
        # `maxChars` floor, which is the budget every slot without one of its
        # own is measured against. delta-10a's `BUDGET.derive` writes that floor
        # back onto the role spec it is handed, and `plates.js` hands out shared
        # objects — so with the manifests collected and written at the end, the
        # last plate to derive won for all of them. 139 of 425 floors came out
        # as a library-wide constant, 96 of them LOOSER than the delivery, and
        # every geometry field agreed perfectly the whole time.
        for field in ("canvas", "exportScale", "playback", "frameCount",
                      "slots"):
            if b.get(field) != s.get(field):
                problems.append(
                    f"{key}: {field} disagrees with the shipped manifest "
                    f"(engine {b.get(field)!r} vs delivery {s.get(field)!r})")
        for role, got, want in _role_diffs(b, s):
            problems.append(
                f"{key}: typeRoles[{role!r}] disagrees with the shipped "
                f"manifest (engine {got!r} vs delivery {want!r})")
    return problems


# Keys inside a typeRole that DESCRIBE the numbers rather than being them. The
# engine writes "…, was 40" where the delivery says "…, authored was 40", and a
# sentence that differs by two words is not a contract violation — reconciling
# on it would train everyone to ignore this check, which is how the thing it
# was added to catch got through in the first place.
_ROLE_PROSE = frozenset({"budget", "note", "why"})


def _role_diffs(built: dict, shipped: dict) -> list[tuple[str, dict, dict]]:
    """Per-role type-spec disagreements, prose excluded.

    A typeRole carries the face, size, weight, colour role and tracking every
    word on screen is set in — and the role-level `maxChars` FLOOR, which is
    the budget every slot without one of its own is measured against. All of it
    is contract, and none of it was reconciled until a shared role object in
    the engine put 139 of 425 floors out by up to 17x with every geometry field
    agreeing perfectly.
    """
    def bare(spec) -> dict:
        if not isinstance(spec, dict):
            return {}
        return {k: v for k, v in spec.items() if k not in _ROLE_PROSE}

    b_roles = built.get("typeRoles") or {}
    s_roles = shipped.get("typeRoles") or {}
    out = []
    for role in sorted(set(b_roles) | set(s_roles)):
        got, want = bare(b_roles.get(role)), bare(s_roles.get(role))
        if got != want:
            out.append((role, got, want))
    return out


def _install(built: dict, delivery: Path, staged: Path, dest: Path,
             outfit: str) -> dict:
    """Replace the installed kit with what was just drawn.

    REPLACES, never merges. Merging is what left stale assets resolvable last
    time: a family that shrank kept its old members, and they stayed addressable
    from a script long after the artwork stopped meaning anything.
    """
    roles_path = delivery / "roles.json"
    roles = json.loads(roles_path.read_text(encoding="utf-8")) if roles_path.exists() else {}
    if not roles:
        print("  (the delivery ships no roles.json — chapter types and host "
              "roles will be empty)")

    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    for fam in sorted({e["family"] for e in built["assets"].values()}):
        shutil.copytree(staged / fam, dest / fam)
        print(f"  {fam}/  {len(list((dest / fam).iterdir()))} files")

    registry = dict(built)
    registry["outfit"] = outfit
    registry["hostRoles"] = {k: v for k, v in roles.get("hostRoles", {}).items()
                             if not k.startswith("_")}
    registry["hostPoses"] = roles.get("hostPoses", {})
    registry["roomRoles"] = {k: v for k, v in roles.get("roomRoles", {}).items()
                             if not k.startswith("_")}
    # THE HOUR THE SET IS AT, one per episode. `hours` maps an hour name to
    # the suffix its keys carry — `dusk` to `-dusk` — so the 24 dusk plates
    # are reachable by the same stems `roomRoles` already names; `episodes`
    # is which of them an episode may be drawn at. Without this the variants
    # are drawn, installed, and addressable by nothing.
    registry["roomHours"] = {k: v for k, v in roles.get("roomHours", {}).items()
                             if not k.startswith("_")}
    registry["chapterTypes"] = roles.get("chapterTypes", {})
    registry["purposes"] = {k: v for k, v in roles.get("purposes", {}).items()
                            if not k.startswith("_")}
    # ONE OUTFIT PER EPISODE. `--outfit` picks which of the five the engine
    # renders into the figure keys; the robe is a different KEY rather than a
    # recolour, so the pipeline needs the block itself to know that
    # `host/medium-robe` is the same shot in other clothes.
    registry["wardrobe"] = {k: v for k, v in roles.get("wardrobe", {}).items()
                            if not k.startswith("_")}
    (dest / REGISTRY_NAME).write_text(
        json.dumps(registry, indent=1, sort_keys=False) + "\n", encoding="utf-8")
    print(f"  {REGISTRY_NAME}")
    return registry


def _verify(repo: Path) -> int:
    """The exhaustive pass: every asset, every frame, every slot, every file."""
    dest = repo / "assets" / PLATES_DIRNAME
    reg = load_registry(dest)

    print(f"registry: {len(reg.assets)} plates, "
          f"{sum(a.frame_count for a in reg.assets.values())} frames, "
          f"outfit {reg.outfit!r}")

    problems: list[str] = []
    named: set[Path] = set()

    for key, a in sorted(reg.assets.items()):
        d = dest / a.family
        for fr in a.frames:
            p = d / fr.png
            named.add(p.resolve())
            if not p.exists():
                problems.append(f"{key}: missing frame {p.relative_to(repo)}")
                continue
            size = _png_size(p)
            if size != tuple(a.delivered):
                problems.append(
                    f"{key}: {fr.png} is {size[0]}x{size[1]}, the registry "
                    f"promises {a.delivered[0]}x{a.delivered[1]}")
            if fr.svg:
                sp = d / fr.svg
                named.add(sp.resolve())
                if not sp.exists():
                    problems.append(f"{key}: missing SVG source {sp.relative_to(repo)}")

        base = d / a.files_png
        named.add(base.resolve())
        if a.files_svg:
            named.add((d / a.files_svg).resolve())
        if not base.exists():
            problems.append(f"{key}: missing base file {base.relative_to(repo)}")
        elif a.base_is_frame:
            # f01 BYTE-IDENTICAL TO BASE. Not "the same drawing" — the same
            # bytes. A base that is its own render pops on the first frame of
            # the loop, and a re-render with the same arguments is exactly the
            # kind of thing that looks right and is not.
            first = d / a.frames[0].png
            if first.exists() and _sha(base) != _sha(first):
                problems.append(
                    f"{key}: the base file is not byte-identical to "
                    f"{a.frames[0].tag} — entering the loop will pop")

        # Slots are checked against the canvas but NOT clipped to it, and a
        # slot outside it is not an error. Twelve annotation slots sit outside
        # their own plate on purpose — `bracket-rows/area` is at x = -880 —
        # because a mark is composited onto something else and its caption
        # lands beside the mark, not inside it. A renderer that clips would
        # silently drop every annotation caption.
        for name, s in a.slots.items():
            # A CONTROL SLOT HAS NO AREA BY DESIGN and is not a defect. Ten of
            # them carry an integer naming a row, a column or a receipt line
            # for the renderer to ring — an index, which has no extent, so the
            # engine writes w = h = 0 and says `control` on the slot.
            #
            # This check could not tell that from a broken box until the
            # manifests were re-emitted verbatim: `control`, `drawn` and
            # `dimensionless` were three of the twenty-nine slot fields the
            # delta-14 whitelist dropped. A zero-area slot that does NOT
            # declare itself a control channel is still a real failure — that
            # is a box nothing can be drawn into, and it stays fatal.
            if s.control:
                continue
            if s.w <= 0 or s.h <= 0:
                problems.append(f"{key}: slot {name!r} has no area")

    orphans = []
    for fam in sorted(EXPECTED_FAMILIES):
        fd = dest / fam
        if not fd.is_dir():
            problems.append(f"family {fam}/ is missing from the installed kit")
            continue
        for p in sorted(fd.iterdir()):
            if p.is_file() and p.resolve() not in named:
                orphans.append(p)
    for fd in sorted(dest.iterdir()):
        if fd.is_dir() and fd.name not in EXPECTED_FAMILIES:
            problems.append(f"family {fd.name}/ is on disk and not expected")

    # AN UNREGISTERED PNG DOES NOT EXIST — and is a failure, not a note. It is
    # how a contact sheet became an addressable asset last time, and how a
    # drawing whose entry had moved stayed resolvable from a script.
    for p in orphans:
        problems.append(f"unregistered file on disk: {p.relative_to(repo)}")

    fams = Counter(a.family for a in reg.assets.values())
    playback = Counter(a.playback for a in reg.assets.values())
    aspects = Counter(a.aspect for a in reg.assets.values())
    print(f"families:  {dict(sorted(fams.items()))}")
    print(f"playback:  {dict(playback)}")
    print(f"aspects:   {dict(sorted(aspects.items()))}")
    print(f"scale:     {sorted({a.export_scale for a in reg.assets.values()})} "
          f"<- read per plate, never assumed")
    print(f"slots:     {sum(len(a.slots) for a in reg.assets.values())} across "
          f"{len(reg.assets)} plates")
    print(f"palette:   {len(reg.palette)} roles: "
          f"{', '.join(sorted(reg.palette))}")
    print(f"chapters:  {len(CHAPTER_TYPES)} types, "
          f"{sum(len(reg.plates_for_chapter(c)) for c in CHAPTER_TYPES)} "
          f"type/plate pairings")
    outside = sum(1 for a in reg.assets.values() for s in a.slots.values()
                  if s.x < 0 or s.y < 0 or s.x + s.w > a.canvas[0]
                  or s.y + s.h > a.canvas[1])
    print(f"slots outside their own canvas: {outside}  "
          f"<- deliberate; never clip a slot")

    if problems:
        print(f"\nFAILED — {len(problems)} problems:")
        for p in problems[:40]:
            print(f"  {p}")
        if len(problems) > 40:
            print(f"  ... and {len(problems) - 40} more")
        print("\nDO NOT COMMIT.")
        return 1

    print(f"\nOK — {len(reg.assets)} plates verified, every frame present at "
          f"its delivered size, every base byte-identical to its first frame, "
          f"nothing on disk the registry does not name.")
    return 0


def _sha(p: Path) -> bytes:
    return hashlib.sha256(p.read_bytes()).digest()


def _png_size(p: Path) -> tuple[int, int]:
    """Read a PNG's dimensions off the IHDR, without decoding the image."""
    with p.open("rb") as fh:
        head = fh.read(24)
    if len(head) < 24 or head[:8] != b"\x89PNG\r\n\x1a\n":
        raise PlateError(f"{p} is not a PNG")
    return (int.from_bytes(head[16:20], "big"), int.from_bytes(head[20:24], "big"))


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("delivery", nargs="?", type=Path,
                    help="the kit delivery: engine/, per-family manifest.json, roles.json")
    ap.add_argument("--check", action="store_true",
                    help="verify the installed kit without rebuilding it")
    ap.add_argument("--outfit", default="shirt",
                    help="which wardrobe to materialise (one per episode; the "
                         "engine renders five and the pipeline uses one)")
    ap.add_argument("--batched", action="store_true",
                    help="build one family per process (14 of them) instead "
                         "of the whole library in one. Slower, and it "
                         "survives a machine that cannot hold the library: "
                         "each process exits and returns its memory before "
                         "the next starts. Use it if a single-pass ingest is "
                         "OOM-killed.")
    ap.add_argument("--only", metavar="FAMILY",
                    help="build ONE family and reconcile only it. For "
                         "regenerating a family a batched run failed on, "
                         "without invalidating the rest. Does not install a "
                         "registry — a partial kit is not a kit.")
    args = ap.parse_args()
    if args.only and args.batched:
        ap.error("--only builds one family; --batched builds all of them "
                 "one at a time. Pick one.")
    if args.only and args.only not in EXPECTED_FAMILIES:
        ap.error(f"unknown family {args.only!r} — the fourteen are "
                 f"{', '.join(sorted(EXPECTED_FAMILIES))}")

    if not args.check and args.delivery is None:
        ap.error("give a delivery directory, or --check")

    try:
        if args.delivery is not None:
            delivery = args.delivery.resolve()
            if not (delivery / "engine").is_dir():
                raise PlateError(f"{delivery} has no engine/ directory")
            print(f"building from {delivery}, outfit {args.outfit!r}")
            staged = REPO / ".kit-build"
            if staged.exists():
                shutil.rmtree(staged)
            try:
                if args.only:
                    return _build_one(delivery, staged, args.outfit, args.only)
                built = (_node_batched(delivery, staged, args.outfit)
                         if args.batched
                         else _node(delivery, staged, args.outfit))
                problems = _reconcile(built["assets"], _shipped_manifests(delivery))
                if problems:
                    print(f"\nFAILED — the engine and the delivery's manifests "
                          f"disagree ({len(problems)}):")
                    for p in problems[:20]:
                        print(f"  {p}")
                    print("\nDO NOT COMMIT.")
                    return 1
                print(f"  reconciled: {len(built['assets'])} plates match the "
                      f"manifests the artwork was signed off against")
                _install(built, delivery, staged,
                         REPO / "assets" / PLATES_DIRNAME, args.outfit)
            finally:
                if staged.exists():
                    shutil.rmtree(staged)
            print()
        return _verify(REPO)
    except PlateError as exc:
        print(f"FAILED — {exc}", file=sys.stderr)
        print("\nDO NOT COMMIT.", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
